### ISSUE TITLE
Cannot run the sh file

### ISSUE THREAD

**Issue by djtom98** [sangyx/DialogueGAT#1]
Trying to replicate the output, I am unable to run the sh file as I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_swd.pkl'
Can you provide instructions on how to recreate this dataset, or maybe a link where I can download it?

**Comment by sangyx** [comment]
Hi, I have updated the repo and added an instruction about the dataset. You can refer to <https://github.com/sangyx/DialogueGAT/blob/main/data_sample/preprocess.ipynb> to construct the dataset from raw HTML files.
